define(function(require){
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/tree/tree');
require('$model/UI2/system/components/justep/scrollView/scrollView');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/output/output');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/button/radio');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/data/baasData');
require('$model/UI2/system/components/bootstrap/breadcrumb/breadcrumb');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/work/common/process/orgDptDialog/index'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='';
	this.__cid='cBzqAJn';
	this._flag_='44348d97c73d5c7d0d2d2d69f2a95dfc';
	this.callParent(contextUrl);
 var __BaasData__ = require("$UI/system/components/justep/data/baasData");new __BaasData__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":false,"defCols":{"sAddress":{"define":"sAddress","label":"","name":"sAddress","relation":"sAddress","type":"String"},"sCode":{"define":"sCode","label":"","name":"sCode","relation":"sCode","type":"String"},"sDescription":{"define":"sDescription","label":"","name":"sDescription","relation":"sDescription","type":"String"},"sFCode":{"define":"sFCode","label":"","name":"sFCode","relation":"sFCode","type":"String"},"sFID":{"define":"sFID","label":"","name":"sFID","relation":"sFID","type":"String"},"sFName":{"define":"sFName","label":"","name":"sFName","relation":"sFName","type":"String"},"sFax":{"define":"sFax","label":"","name":"sFax","relation":"sFax","type":"String"},"sID":{"define":"sID","label":"","name":"sID","relation":"sID","type":"String"},"sLevel":{"define":"sLevel","label":"","name":"sLevel","relation":"sLevel","rules":{"integer":true},"type":"Integer"},"sLongName":{"define":"sLongName","label":"","name":"sLongName","relation":"sLongName","type":"String"},"sName":{"define":"sName","label":"","name":"sName","relation":"sName","type":"String"},"sNodeKind":{"define":"sNodeKind","label":"","name":"sNodeKind","relation":"sNodeKind","type":"String"},"sOrgKindID":{"define":"sOrgKindID","label":"","name":"sOrgKindID","relation":"sOrgKindID","type":"String"},"sParent":{"define":"sParent","label":"","name":"sParent","relation":"sParent","type":"String"},"sPersonID":{"define":"sPersonID","label":"","name":"sPersonID","relation":"sPersonID","type":"String"},"sPhone":{"define":"sPhone","label":"","name":"sPhone","relation":"sPhone","type":"String"},"sSequence":{"define":"sSequence","label":"","name":"sSequence","relation":"sSequence","type":"String"},"sValidState":{"define":"sValidState","label":"","name":"sValidState","relation":"sValidState","rules":{"integer":true},"type":"Integer"},"sWxDeptID":{"define":"sWxDeptID","label":"","name":"sWxDeptID","relation":"sWxDeptID","rules":{"integer":true},"type":"Integer"},"sZip":{"define":"sZip","label":"","name":"sZip","relation":"sZip","type":"String"},"version":{"define":"version","label":"","name":"version","relation":"version","rules":{"integer":true},"type":"Integer"}},"directDelete":true,"events":{},"filters":{"filter0":"sOrgKindID in('ogn','dpt')"},"idColumn":"sID","limit":20,"queryAction":"querySa_oporg","saveAction":"saveSa_oporg","tableName":"sa_oporg","treeOption":{"isDelayLoad":true,"parentRelation":"sParent"},"url":"/org/loadPerson","xid":"mainData"});
 new __BaasData__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"sAddress":{"define":"sAddress","label":"sAddress","name":"sAddress","relation":"sAddress","type":"String"},"sCode":{"define":"sCode","label":"sCode","name":"sCode","relation":"sCode","type":"String"},"sDescription":{"define":"sDescription","label":"sDescription","name":"sDescription","relation":"sDescription","type":"String"},"sFCode":{"define":"sFCode","label":"sFCode","name":"sFCode","relation":"sFCode","type":"String"},"sFID":{"define":"sFID","label":"sFID","name":"sFID","relation":"sFID","type":"String"},"sFName":{"define":"sFName","label":"sFName","name":"sFName","relation":"sFName","type":"String"},"sFax":{"define":"sFax","label":"sFax","name":"sFax","relation":"sFax","type":"String"},"sID":{"define":"sID","label":"sID","name":"sID","relation":"sID","type":"String"},"sLevel":{"define":"sLevel","label":"sLevel","name":"sLevel","relation":"sLevel","rules":{"integer":true},"type":"Integer"},"sLongName":{"define":"sLongName","label":"sLongName","name":"sLongName","relation":"sLongName","type":"String"},"sName":{"define":"sName","label":"sName","name":"sName","relation":"sName","type":"String"},"sNodeKind":{"define":"sNodeKind","label":"sNodeKind","name":"sNodeKind","relation":"sNodeKind","type":"String"},"sOrgKindID":{"define":"sOrgKindID","label":"sOrgKindID","name":"sOrgKindID","relation":"sOrgKindID","type":"String"},"sParent":{"define":"sParent","label":"sParent","name":"sParent","relation":"sParent","type":"String"},"sPersonID":{"define":"sPersonID","label":"sPersonID","name":"sPersonID","relation":"sPersonID","type":"String"},"sPhone":{"define":"sPhone","label":"sPhone","name":"sPhone","relation":"sPhone","type":"String"},"sSequence":{"define":"sSequence","label":"sSequence","name":"sSequence","relation":"sSequence","type":"String"},"sValidState":{"define":"sValidState","label":"sValidState","name":"sValidState","relation":"sValidState","rules":{"integer":true},"type":"Integer"},"sWxDeptID":{"define":"sWxDeptID","label":"sWxDeptID","name":"sWxDeptID","relation":"sWxDeptID","rules":{"integer":true},"type":"Integer"},"sZip":{"define":"sZip","label":"sZip","name":"sZip","relation":"sZip","type":"String"},"version":{"define":"version","label":"version","name":"version","relation":"version","rules":{"integer":true},"type":"Integer"}},"directDelete":false,"events":{},"filters":{"filter0":"sOrgKindID in('ogn','dpt')"},"idColumn":"sID","limit":-1,"queryAction":"querySa_oporg","saveAction":"saveSa_oporg","tableName":"sa_oporg","url":"/org/loadPerson","xid":"dptData"});
}}); 
return __result;});